export interface AcceptanceMessage { speaker: string; text: string; final?: boolean; interrupted?: boolean; historical?: boolean; messageId?: string | null; sourceLabel?: string | null; displayedAt?: string | null; historyIndex?: number | null; chapterLabel?: string | null }
export interface AcceptanceStep { turnId: string | number; utterance: string; startedAtMs: number; endedAtMs: number; settled: boolean; failureLayer?: string; messages?: AcceptanceMessage[]; proposal?: { proposalId: string; label: string; status: string } | null; agreedPlan?: { sourceTurnId: string | number; requestQuote: string; acceptedReplyQuote: string }; acceptedProposal?: { sourceTurnId: string | number; proposalQuote: string } }
export interface AcceptanceEvent { type: string; atMs: number; name?: string; callRef?: number; replyRef?: number; isError?: boolean; actionStatus?: string; proposalRef?: number }
export interface AcceptanceFinding { code: string; blocking?: boolean; [key: string]: unknown }
export function evaluateAcceptanceBehavior(options?: { steps?: AcceptanceStep[]; events?: AcceptanceEvent[]; contract?: 'direct_actions' | 'confirmed_actions'; confirmations?: Array<{ status: string; label: string; confirmedAtMs: number }> }): {
  status: 'pass' | 'blocked' | 'review_required'; materialDefects: AcceptanceFinding[]; uncertainties: AcceptanceFinding[];
  turns: Array<{ turnId: string | number; request: string; intent: string; sourceWindow: { startedAtMs: number; endedAtMs: number }; replies: Array<{ text: string; messageId: string | null; sourceLabel: string | null; displayedAt: string | null; historyIndex: number | null; chapterLabel: string | null; final: boolean; interrupted: boolean }>; tools: Array<{ name: string | null; callRef: number | null; replyRef: number | null; atMs: number; resultAtMs: number | null; outcome: string; proposalRef?: number; executed?: false }>; agreedPlanSourceTurnId?: string | number; acceptedProposalSourceTurnId?: string | number }>;
  reviewedToolCalls: number; boundary: string; contract: string;
};
